######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 16 10:47:42 2012
######################################################################

QT += webkit

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += flwebview.h
SOURCES += flwebview.cpp main.cpp
